import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { Script } from 'node:vm';
const root = new URL('../', import.meta.url);
const modules = ['config', 'grid', 'kwin-adapter', 'main'];
let bundle = '// Generated by npm run build. Edit src/, not this file.\n';

for (const name of modules) {
  let source = await readFile(new URL(`src/${name}.js`, root), 'utf8');

  source = source
    .replace(/^import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];\r?\n/gm, '')
    .replace(/^export /gm, '');

  if (/^(import|export)\s/m.test(source))
    throw new Error('Unsupported module syntax in ' + name);

  bundle += '\n// ' + name + '\n' + source;
}

const entrySource = await readFile(
  new URL('scripts/kwin-entry.js', root),
  'utf8',
);

bundle += '\n' + entrySource;
new Script(bundle, { filename: 'main.js' });

await mkdir(new URL('package/contents/code/', root), { recursive: true });

await writeFile(new URL('package/contents/code/main.js', root), bundle);

// A ZIP with stored entries: no external archiver or build dependency.
function crc32(bytes) {
  let crc = 0xffffffff;

  for (const b of bytes) {
    crc ^= b;
    for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }

  return (crc ^ 0xffffffff) >>> 0;
}

const metadata = await readFile(new URL('package/metadata.json', root));

const files = [
  ['metadata.json', metadata],
  ['contents/code/main.js', Buffer.from(bundle)],
];
const local = [],
  central = [];
let offset = 0;
for (const [name, data] of files) {
  const filename = Buffer.from(name),
    crc = crc32(data),
    head = Buffer.alloc(30),
    entry = Buffer.alloc(46);
  head.writeUInt32LE(0x04034b50, 0);
  head.writeUInt16LE(20, 4);
  head.writeUInt16LE(0x21, 12);
  head.writeUInt32LE(crc, 14);
  head.writeUInt32LE(data.length, 18);
  head.writeUInt32LE(data.length, 22);
  head.writeUInt16LE(filename.length, 26);
  entry.writeUInt32LE(0x02014b50, 0);
  entry.writeUInt16LE(20, 4);
  entry.writeUInt16LE(20, 6);
  entry.writeUInt16LE(0x21, 14);
  entry.writeUInt32LE(crc, 16);
  entry.writeUInt32LE(data.length, 20);
  entry.writeUInt32LE(data.length, 24);
  entry.writeUInt16LE(filename.length, 28);
  entry.writeUInt32LE(offset, 42);
  local.push(head, filename, data);
  central.push(entry, filename);
  offset += head.length + filename.length + data.length;
}

const directory = Buffer.concat(central),
  end = Buffer.alloc(22);
end.writeUInt32LE(0x06054b50, 0);
end.writeUInt16LE(files.length, 8);
end.writeUInt16LE(files.length, 10);
end.writeUInt32LE(directory.length, 12);
end.writeUInt32LE(offset, 16);

await mkdir(new URL('dist/', root), { recursive: true });

await writeFile(
  new URL('dist/kwin-compose.kwinscript', root),
  Buffer.concat([...local, directory, end]),
);

console.log('Built package/ and dist/kwin-compose.kwinscript');
